set_volume_mount_path: "/mnt/backup"

set_tower_organization_name: "My organisation"
set_remote_server_ansible_user: "[name]"
set_remote_server_inventory_name: "Remote Server"
set_remote_server_ssh_key_credentials_name: "SSH key for remote server"
set_remote_server_ssh_key_path: "~/.ssh/[name]"
set_remote_server_host_url: "server.example.com"
set_remote_server_host_name: "My remote server"

set_tower_project_name: "Database backup"
set_tower_project_git_url: "https://github.com/daljitdokal/raspberry-pi-ubuntu-server-k3s-awx-ansible-automated-setup.git"
set_tower_job_template_name: "Database daily backup"
set_tower_job_template_playbook_name: "post-install/playbook/mysql-backup/playbook_mysql_database_backup.yaml"
set_remote_db_backup_folder_path: "/backup/"
set_local_db_backup_folder_path: "/mnt/backup/databases/"
set_remote_db_file_name_pattern_to_delete: "database_name_202*"

set_tower_database_credential_type_name: "My database access"
set_remote_server_database_credentials_name: "My database credential"
db_name: ""
db_user_name: "" 

db_user_password: ""
set_remote_server_ssh_key_pass: ""

set_schedule: "DTSTART;TZID=Pacific/Auckland:20230101T050000 RRULE:FREQ=DAILY;INTERVAL=1"
