set_volume_mount_path: ""

set_tower_organization_name: ""
set_remote_server_ansible_user: ""
set_remote_server_inventory_name: ""
set_remote_server_ssh_key_credentials_name: ""
set_remote_server_ssh_key_path: ""
set_remote_server_host_url: ""
set_remote_server_host_name: ""

set_tower_project_name: "Database backup"
set_tower_project_git_url: "https://github.com/daljitdokal/raspberry-pi-ubuntu-server-k3s-awx-ansible-automated-setup.git"
set_tower_job_template_name: "Database daily backup"
set_tower_job_template_playbook_name: "post-install/playbook/mysql-backup/playbook_mysql_database_backup.yaml"
set_remote_db_backup_folder_path: ""
set_local_db_backup_folder_path: ""
set_remote_db_file_name_pattern_to_delete: ""

set_tower_database_credential_type_name: ""
set_remote_server_database_credentials_name: ""
db_name: ""
db_user_name: "" 

set_schedule: "DTSTART;TZID=Pacific/Auckland:20230101T050000 RRULE:FREQ=DAILY;INTERVAL=1"

db_user_password: ""
set_remote_server_ssh_key_pass: ""
