set_tower_organization_name: ""
set_remote_server_ansible_user: ""
set_remote_server_inventory_name: ""
set_remote_server_ssh_key_credentials_name: ""
set_remote_server_ssh_key_path: ""
set_remote_server_ssh_key_pass: ""
set_remote_server_host_url: ""
set_remote_server_host_name: ""

set_tower_project_name: "Database backup"
set_tower_project_git_url: "https://github.com/daljitdokal/raspberry-pi-ubuntu-server-k3s-awx-ansible-automated-setup.git"
set_tower_job_template_name: "Database daily backup"
set_tower_job_template_playbook_name: "post-install/playbook/mysql-backup/playbook_mysql_database_backup.yaml"
set_remote_db_backup_folder_path: "backup"
set_local_db_backup_folder_path: "backup"
set_remote_db_file_name_pattern_to_delete: ""
set_tower_credential_type_name: ""

set_tower_credential_type_db_name: ""
set_tower_credential_type_db_user_name: "" 
set_tower_credential_type_db_user_password: "" 